version = 1

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/quark-links/quark-cli"

[[transformers]]
name = "gofmt"
enabled = true