name: vh7-cli
version: git
summary: A command-line interface for VH7.
description: |
  A lovely command-line interface made for VH7. VH7 command-line allows you to
  quickly create short links, share your code and share files without leaving
  your terminal.
license: MIT

confinement: strict
base: core18

parts:
  vh7-cli:
    plugin: go
    source: .

apps:
  vh7-cli:
    command: bin/vh7-cli
    plugs:
      - network
      - removable-media
      - home
