name: CI
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Build
        run: go build -o ./ -v ./...
      - name: Test
        run: go test -v ./...
  tag-new-version:
    runs-on: ubuntu-20.04
    outputs:
      current-version: ${{ steps.detect-and-tag-version.outputs.current-version }}
      tag: ${{ steps.detect-and-tag-version.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Detect and Tag New Version
        id: detect-and-tag-version
        uses: salsify/action-detect-and-tag-new-version@v2
        with:
          version-command: "grep BuildVersion version.go | cut -d'=' -f 2 | tr -d '\"' | xargs"
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        if: ${{ steps.detect-and-tag-version.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.detect-and-tag-version.outputs.tag }}
          release_name: Release ${{ steps.detect-and-tag-version.outputs.current-version }}
          draft: false
          prerelease: false
  release:
    needs:
      - build
      - tag-new-version
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: linux
            arch: "386"
          - os: windows
            arch: "386"
          - os: windows
            arch: amd64
          - os: windows
            arch: arm64
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' && needs.tag-new-version.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: wangyoucao577/go-release-action@v1.15
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.os }}
          goarch: ${{ matrix.arch }}
          extra_files: LICENSE README.md
          release_tag: ${{ needs.tag-new-version.outputs.tag }}
