name: CI
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node 14
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      - name: Get cache path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache node_modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --dev
      - name: Linter
        run: yarn run lint
      - name: Compile TypeScript
        run: yarn run build
      - name: Build executables
        run: yarn run release
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: dist/binaries/
  tag-new-version:
    runs-on: ubuntu-latest
    outputs:
      current-version: ${{ steps.detect-and-tag-version.outputs.current-version }}
      tag: ${{ steps.detect-and-tag-version.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Detect and Tag New Version
        id: detect-and-tag-version
        uses: salsify/action-detect-and-tag-new-version@v2
  release:
    needs:
      - build
      - tag-new-version
    runs-on: ubuntu-latest
    #if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' && needs.tag-new-version.outputs.tag }}
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: binaries
          path: dist/binaries/
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.tag-new-version.outputs.tag }}
          release_name: Release ${{ needs.tag-new-version.outputs.current-version }}
          draft: false
          prerelease: false
      - name: Upload Windows Binary
        id: upload-asset-windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: dist/binaries/vh7cli-win.exe
          asset_name: vh7cli-${{ needs.tag-new-version.outputs.current-version }}-windows.exe
          asset_content_type: application/x-msdownload
      - name: Upload Linux Binary
        id: upload-asset-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: dist/binaries/vh7cli-linux
          asset_name: vh7cli-${{ needs.tag-new-version.outputs.current-version }}-linux
          asset_content_type: application/x-executable
      - name: Upload MacOS Binary
        id: upload-asset-macos
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: dist/binaries/vh7cli-macos
          asset_name: vh7cli-${{ needs.tag-new-version.outputs.current-version }}-macos
          asset_content_type: application/x-executable
